listen:
  port: 8082
mysql:
  dsn: root:nil@tcp(192.168.31.46:3306)/sso?parseTime=true
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxIdleTime: 5
  connMaxLifetime: 30
redis:
  dsn: 127.0.0.1:6379
  db: 8
  poolSize: 100
  minIdleConns: 10
  connMaxIdleTime: 5 #单位为分钟
  connMaxLifetime: 30 #单位为分钟
  ttl: 60 #单位为秒
